services:
  - type: web
    name: my-web-service
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y gcc libatlas-base-dev
      pip install --upgrade setuptools
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
